#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Weather_App_V1.Resource", IsApplication=true)]

namespace Weather_App_V1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Clear = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Clouds = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Cloudy = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Drizzle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Earth1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int GPS = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int NoImage = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int NZBlue = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Rain = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int search = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Snow = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Splash = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Thunderstorm = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int btnGPS = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int btnSearch = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int gridLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060012
			public const int imgDay1 = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int imgDay2 = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int imgDay3 = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int imgDay4 = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int imgDay5 = 2131099678;
			
			// aapt resource value: 0x7f06000c
			public const int imgMain = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout10 = 2131099673;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout11 = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout12 = 2131099667;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout13 = 2131099664;
			
			// aapt resource value: 0x7f060028
			public const int linearLayout14 = 2131099688;
			
			// aapt resource value: 0x7f060026
			public const int linearLayout15 = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int linearLayout16 = 2131099684;
			
			// aapt resource value: 0x7f060022
			public const int linearLayout17 = 2131099682;
			
			// aapt resource value: 0x7f060020
			public const int linearLayout18 = 2131099680;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout2 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout3 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout4 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout5 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout6 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout7 = 2131099663;
			
			// aapt resource value: 0x7f06001f
			public const int linearLayout8 = 2131099679;
			
			// aapt resource value: 0x7f06001c
			public const int linearLayout9 = 2131099676;
			
			// aapt resource value: 0x7f060007
			public const int txtCity = 2131099655;
			
			// aapt resource value: 0x7f060011
			public const int txtDay1 = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int txtDay2 = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int txtDay3 = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int txtDay4 = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int txtDay5 = 2131099677;
			
			// aapt resource value: 0x7f06000e
			public const int txtDescription = 2131099662;
			
			// aapt resource value: 0x7f060021
			public const int txtDetails1 = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int txtDetails2 = 2131099683;
			
			// aapt resource value: 0x7f060025
			public const int txtDetails3 = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int txtDetails4 = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int txtDetails5 = 2131099689;
			
			// aapt resource value: 0x7f060009
			public const int txtMain = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int txtSearch = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int txtTemp = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Splash = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
